spring:
  application:
    name: spring-cloud-feign-client-hystrix
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

server:
  port: 8081
feign:
  hystrix:
    enabled: true

ribbon:
  okhttp:
    enabled: true

logging:
  level:
    xin:
      tianhui:
        cloud: debug