spring:
  application:
    name: spring-cloud-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test
          uri: lb://spring-cloud-feign
          predicates:
            - Query=name
            - Path=/feign-server/**
          filters:
            - StripPrefix=1

server:
  port: 8082